0.1.x
strangelove-ventures/wadesta pull request #121
Opened 2023-11-10 05:41 UTC by codingki

v0.1.0-beta.2: https://npmjs.com/package/graz/v/0.1.0-beta.2
docs: https://0-1-x-iteration-1.graz.pages.dev/docs/

## 0.1.0 Breaking Changes

### `<GrazProvider/>`

`grazOptions` is required to provide a `ChainInfo[]` to the `chains` param. [Read more](./provider/grazProvider.md)

```diff
const cosmoshub = {
  chainId: "cosmoshub-4",
  chainName: "Cosmos Hub",
  //...
}
- <GrazProvider>
+ <GrazProvider grazOptions={{
+   chains: [cosmoshub]
+ }}>
  // children
  </GrazProvider>
```

`defaultChain` removed from `grazOptions`

### Removed `GrazChain` type

We are using [`ChainInfo` from `@keplr-wallet/types`](https://github.com/chainapsis/keplr-wallet/blob/master/packages/types/src/chain-info.ts#L5-L46) instead of `GrazChain`

Our initial intention having `GrazChain` is for adding and only using required value for interacting with signingClients. We adding rpcHeaders and gas in there for interacting with clients and signingClient for simplicity, but this can make a different problem when you already have a ChainInfo you will need to mutate those constants. [Read RFC](https://github.com/orgs/graz-sh/discussions/115).

For adding rpcHeaders and gas, we can add it in `GrazProvider` on `grazOptions.chainsConfig` to provide those values.

```ts
interface ChainConfig {
  rpcHeaders?: Dictionary<string>;
  gas?: { price: string; denom: string };
}

type ChainsConfig = Record<string, ChainConfig>;
```

```diff
// previous GrazChain
const cosmoshub = {
  chainId: "cosmoshub-4",
  chainName: "Cosmos Hub",
- rpcHeaders: {
-   "custom-header": "custom-value"
-  },
- gas: {
-   price: "0.025",
-   denom: "uatom"
- }
}

  <GrazProvider grazOptions={
    chains: [cosmoshub],
+   chainsConfig:{
+     "cosmoshub-4": {
+       rpcHeaders: {
+         "custom-header": "custom-value"
+       },
+       gas: {
+         price: "0.025",
+         denom: "uatom"
+       }
+      }
+   }
  }>
  // children
  </GrazProvider>
```

When you connect you don't need `GrazChain` anymore, you only need the `chainId`

```diff
  const { connect } = useConnect();
  connect({
-   chain: cosmoshub,
+   chainId: "cosmoshub-4", // chainId receive string | string[]
    // ...
  })

```

### `useConnect`

```diff
const { connect } = useConnect();
  connect({
-   chain: cosmoshub,
+   chainId: "cosmoshub-4", // chainId receive string | string[]
    // ...
  })
```

### `ConnectResult`

return type of `connect` in `useConnect` and `onConnect` params

```diff
interface ConnectResult {
- account: Key;
+ account: Record<string, Key>
  walletType: WalletType;
- chain: GrazChain;
+ chains: ChainInfo[];
}
```

### `useBalance`

```diff
- const balance = useBalance(denom, bech32Address);
+ const balance = useBalance({ denom, bech32Address });
```

### `useBalances`

```diff
- const balances = useBalances(denom, bech32Address);
+ const balances = useBalances({ denom, bech32Address });
```

### `useBalanceStaked`

```diff
- const balanceStaked = useBalances(bech32Address);
+ const balanceStaked = useBalanceStaked({ bech32Address });
```

### `useQuerySmart`

```diff
- const querySmart = useQuerySmart(address, message);
+ const querySmart = useQuerySmart({ address, message });
```

### `useQueryRaw`

```diff
- const queryRaw = useQueryRaw(address, key);
+ const queryRaw = useQueryRaw({ address, key });
```

2023-11-14 13:26 UTC, grikomsn requested changes

2023-11-14 13:26 UTC, grikomsn commented on CONTRIBUTING.md
> +Currently there were no stable library for cosmos wallets. We were inspired by the patterns in [`wagmi`](https://wagmi.sh) in the Etherium ecosystem.
```suggestion
At the time there were no stable libraries for cosmos wallets. We were inspired by the patterns in [`wagmi`](https://wagmi.sh) in the Ethereum ecosystem.
```

2023-11-14 13:26 UTC, grikomsn commented on README.md
> +To avoid version missmatch we dcided to make these packages as peer dependencies
```suggestion
To avoid version mismatch we decided to make these packages as peer dependencies:
```

2023-11-14 13:26 UTC, grikomsn commented on docs/docs/contributing.md
> +Currently there were no stable library for cosmos wallets. We were inspired by the patterns in [`wagmi`](https://wagmi.sh) in the Etherium ecosystem.
```suggestion
At the time there were no stable libraries for cosmos wallets. We were inspired by the patterns in [`wagmi`](https://wagmi.sh) in the Ethereum ecosystem.
```

2023-11-14 13:26 UTC, grikomsn commented on docs/docs/getting-started.mdx
> +To avoid version missmatch we dcided to make these packages as peer dependencies
```suggestion
To avoid version mismatch we decided to make these packages as peer dependencies:
```

2023-11-14 21:27 UTC, grikomsn approved these changes

2023-11-17 09:20 UTC, merged

2023-11-21 09:37 UTC, apollo-sturdy commented
With this change, where do we find gas prices? We must hardcode them in our app? Seems like they exist in chain-registry, so would be great if they can be fetched when setting up graz.

2023-11-21 09:59 UTC, codingki commented
@apollo-sturdy previously we need to hardcode too in graz chain. now you need to do this https://graz.sh/docs/migration-guide#removed-grazchain-type

2023-11-22 15:10 UTC, apollo-sturdy commented
> @apollo-sturdy previously we need to hardcode too in graz chain. now you need to do this https://graz.sh/docs/migration-guide#removed-grazchain-type

Is it worth updating the `--generate` command to fetch them from chain-registry?

2023-11-22 15:17 UTC, grikomsn commented
@apollo-sturdy `graz --generate` is getting the data from the chain registry, which you can check on the CLI script here: https://github.com/graz-sh/graz/blob/dev/packages/graz/src/cli.mjs

We are still researching on another solution to generate chain info metadatas, which you can also check here: https://github.com/graz-sh/wadesta